sudo: required
language: python
python:
  - "3.6"
services:
  - docker

# Next run the tests in Travis CI's normal Python environment.
install:
  - pip install --upgrade pip
  # This also installs ORR's dependencies.
  # TODO: make it so we don't need to install any third-party libraries
  #  since running Docker doesn't require the dependencies.
  - pip install -e submodules/osv-results-reporter/src/
script:
  - python generate.py --skip-pdf
deploy:
  provider: pages
  # The generate.py script builds the output to the following directory.
  local_dir: docs
  skip_cleanup: true
  # This environment variable is set in the settings page of your repository.
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
